[
  {
    "ProfileName": "AI-Specific-Header-Disclosure",
    "Name": "",
    "Enabled": true,
    "Scanner": 2,
    "Author": "@bountysecurity",
    "Payloads": [],
    "Encoder": [],
    "UrlEncode": false,
    "CharsToUrlEncode": "",
    "Grep": [
      "true,,Regex,,(?i)(x-ai-backend:|x-rag-provider:|x-llm-provider:|x-openai-model:|x-anthropic-model:|x-embedding-model:|x-mcp-enabled:)",
      "true,OR,Regex,,(?i)^x-model\\s*:.*\\b(gpt|claude|gemini|llama|mistral|qwen|command-r|mixtral)\\b.*$"
    ],
    "Tags": [
      "AI",
      "All"
    ],
    "PayloadResponse": false,
    "NotResponse": false,
    "TimeOut1": "",
    "TimeOut2": "",
    "isTime": false,
    "contentLength": "",
    "iscontentLength": false,
    "CaseSensitive": false,
    "ExcludeHTTP": false,
    "OnlyHTTP": true,
    "IsContentType": false,
    "ContentType": "",
    "HttpResponseCode": "",
    "NegativeCT": false,
    "IsResponseCode": false,
    "ResponseCode": "",
    "NegativeRC": false,
    "urlextension": "",
    "isurlextension": false,
    "NegativeUrlExtension": false,
    "isHeaderValue": false,
    "sequence": false,
    "NewHeaders": [],
    "MatchType": 2,
    "Scope": 2,
    "scanScope": 0,
    "RedirType": 0,
    "MaxRedir": 0,
    "requestType": 1,
    "rawRequest": "",
    "payloadPosition": 0,
    "payloadsFile": "",
    "grepsFile": "",
    "IssueName": "AI-Specific HTTP Header Disclosure",
    "IssueSeverity": "Information",
    "IssueConfidence": "Firm",
    "IssueDetail": "The application exposes HTTP headers strongly associated with AI backend, model provider, RAG, embeddings, or MCP functionality.",
    "RemediationDetail": "Remove or normalize non-essential headers that disclose AI backend, provider, model, embedding, or MCP details.",
    "IssueBackground": "AI-specific response headers can reveal infrastructure, providers, and internal architecture useful during reconnaissance.",
    "RemediationBackground": "",
    "Header": [],
    "VariationAttributes": [],
    "InsertionPointType": [],
    "Scanas": false,
    "Scantype": 0,
    "pathDiscovery": false,
    "changeHttpRequest": false,
    "showIssue": false,
    "changeHttpRequestType": 0,
    "steps": []
  }
]