[
  {
    "ProfileName": "Health-Status-Metadata-Exposure",
    "Name": "",
    "Enabled": true,
    "Scanner": 2,
    "Author": "@bountysecurity",
    "Payloads": [],
    "Encoder": [],
    "UrlEncode": false,
    "CharsToUrlEncode": "",
    "Grep": [
      "true,,Regex,,(?i)\\b(rag_enabled|mcp_enabled|embedding_model|vector_db|prompt_tokens|completion_tokens|total_tokens)\\b",
      "true,Or,Regex,,(?i)\\b(model_name|model_provider|llm_provider|service_version)\\b"
    ],
    "Tags": [
      "AI",
      "All"
    ],
    "PayloadResponse": false,
    "NotResponse": false,
    "TimeOut1": "",
    "TimeOut2": "",
    "isTime": false,
    "contentLength": "",
    "iscontentLength": false,
    "CaseSensitive": false,
    "ExcludeHTTP": true,
    "OnlyHTTP": false,
    "IsContentType": true,
    "ContentType": "application/json,text/plain",
    "HttpResponseCode": "",
    "NegativeCT": false,
    "IsResponseCode": false,
    "ResponseCode": "",
    "NegativeRC": false,
    "urlextension": "",
    "isurlextension": false,
    "NegativeUrlExtension": false,
    "isHeaderValue": false,
    "sequence": false,
    "NewHeaders": [],
    "MatchType": 2,
    "Scope": 2,
    "scanScope": 0,
    "RedirType": 0,
    "MaxRedir": 0,
    "requestType": 1,
    "rawRequest": "",
    "payloadPosition": 0,
    "payloadsFile": "",
    "grepsFile": "",
    "IssueName": "AI Health or Status Metadata Exposure",
    "IssueSeverity": "Information",
    "IssueConfidence": "Firm",
    "IssueDetail": "The response appears to expose AI-related operational metadata such as RAG, MCP, embeddings, token usage, model provider, or service versioning.",
    "RemediationDetail": "Restrict health and status endpoints and avoid returning AI model, provider, RAG, MCP, embeddings, and token telemetry in public responses.",
    "IssueBackground": "Operational endpoints sometimes disclose backend AI configuration that is valuable during reconnaissance and attack planning.",
    "RemediationBackground": "",
    "Header": [],
    "VariationAttributes": [],
    "InsertionPointType": [],
    "Scanas": false,
    "Scantype": 0,
    "pathDiscovery": false,
    "changeHttpRequest": false,
    "showIssue": false,
    "changeHttpRequestType": 0,
    "steps": []
  }
]