[
  {
    "ProfileName": "OpenAI-Compatible-API-Fingerprinting",
    "Name": "",
    "Enabled": true,
    "Scanner": 2,
    "Author": "@bountysecurity",
    "Payloads": [],
    "Encoder": [],
    "UrlEncode": false,
    "CharsToUrlEncode": "",
    "Grep": [
      "true,,Regex,,(?i)\\b(prompt_tokens|completion_tokens|total_tokens)\\b",
      "true,And,Regex,,(?i)\\bchoices\\b",
      "true,And,Regex,,(?i)\\bmodel\\b",
      "true,Or,Regex,,(?i)\\bchatcmpl-[a-z0-9]+\\b"
    ],
    "Tags": [
      "AI",
      "All"
    ],
    "PayloadResponse": false,
    "NotResponse": false,
    "TimeOut1": "",
    "TimeOut2": "",
    "isTime": false,
    "contentLength": "",
    "iscontentLength": false,
    "CaseSensitive": false,
    "ExcludeHTTP": true,
    "OnlyHTTP": false,
    "IsContentType": true,
    "ContentType": "application/json",
    "HttpResponseCode": "",
    "NegativeCT": false,
    "IsResponseCode": false,
    "ResponseCode": "",
    "NegativeRC": false,
    "urlextension": "",
    "isurlextension": false,
    "NegativeUrlExtension": false,
    "isHeaderValue": false,
    "sequence": false,
    "NewHeaders": [],
    "MatchType": 2,
    "Scope": 2,
    "scanScope": 0,
    "RedirType": 0,
    "MaxRedir": 0,
    "requestType": 1,
    "rawRequest": "",
    "payloadPosition": 0,
    "payloadsFile": "",
    "grepsFile": "",
    "IssueName": "OpenAI-Compatible API Response Fingerprinting",
    "IssueSeverity": "Information",
    "IssueConfidence": "Firm",
    "IssueDetail": "The response appears to match an OpenAI-compatible schema and exposes model or token usage metadata.",
    "RemediationDetail": "Review whether the endpoint should be publicly exposed and whether model and usage metadata should be returned to untrusted clients.",
    "IssueBackground": "OpenAI-compatible APIs can disclose model-serving behavior and operational metadata that are useful during reconnaissance.",
    "RemediationBackground": "",
    "Header": [],
    "VariationAttributes": [],
    "InsertionPointType": [],
    "Scanas": false,
    "Scantype": 0,
    "pathDiscovery": false,
    "changeHttpRequest": false,
    "showIssue": false,
    "changeHttpRequestType": 0,
    "steps": []
  }
]